### ISSUE TITLE
[新官網] 認識我們

### ISSUE THREAD

**Issue by mirumodapon** [COSCUP/coscup.org#6]

**Comment by bessyhuang** [comment]
討論摘要：
- 可參考「輪播圖」方式，顯示照片
- 可參考 [SITCON 支持我們](https://sitcon.org/2024/sponsor/)：Flickr 照片 x 統計數據
- 可劃分幾個主要的主題區塊：COSCUP 起源、組成與組織、年會活動、海內外贊助、活動剪影
  - 「年會活動」放置每年都有的活動，如：Lightening Talk、BoF / Hacking Room、形象照、主議程軌

**Comment by bessyhuang** [comment]
- [x] 照片輪播圖 (#25)
